"""add customer digibills

Revision ID: 1481d5579431
Revises: f4397b995886
Create Date: 2026-09-20 12:06:59.233324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1481d5579431"
down_revision: Union[str, Sequence[str], None] = "f4397b995886"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_digibills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("digibill_id", sa.String(length=20), nullable=False),
        sa.Column("uploaded_bill_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=True),
        sa.Column("invoice_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "retailer_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "customer_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "products", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "payment", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "warranty_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "confidence_scores",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "extraction_notes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_bill_id"],
            ["customer_uploaded_bills.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_digibills_customer_id"),
        "customer_digibills",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_digibills_digibill_id"),
        "customer_digibills",
        ["digibill_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_customer_digibills_uploaded_bill_id"),
        "customer_digibills",
        ["uploaded_bill_id"],
        unique=True,
    )
    op.alter_column(
        "customer_bill_extractions",
        "status",
        existing_type=sa.VARCHAR(length=30),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("customer_bill_extractions_uploaded_bill_id_key"),
        "customer_bill_extractions",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_customer_bill_extractions_uploaded_bill_id"),
        table_name="customer_bill_extractions",
    )
    op.create_index(
        op.f("ix_customer_bill_extractions_uploaded_bill_id"),
        "customer_bill_extractions",
        ["uploaded_bill_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_bill_extractions_uploaded_bill_id"),
        table_name="customer_bill_extractions",
    )
    op.create_index(
        op.f("ix_customer_bill_extractions_uploaded_bill_id"),
        "customer_bill_extractions",
        ["uploaded_bill_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("customer_bill_extractions_uploaded_bill_id_key"),
        "customer_bill_extractions",
        ["uploaded_bill_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "customer_bill_extractions",
        "status",
        existing_type=sa.VARCHAR(length=30),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_customer_digibills_uploaded_bill_id"),
        table_name="customer_digibills",
    )
    op.drop_index(
        op.f("ix_customer_digibills_digibill_id"),
        table_name="customer_digibills",
    )
    op.drop_index(
        op.f("ix_customer_digibills_customer_id"),
        table_name="customer_digibills",
    )
    op.drop_table("customer_digibills")
    # ### end Alembic commands ###
