"""add subscription plans

Revision ID: 177d5c43e244
Revises: 973b68b6ecc3
Create Date: 2026-08-15 21:38:03.912225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "177d5c43e244"
down_revision: Union[str, Sequence[str], None] = "973b68b6ecc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("customer_type", sa.String(length=30), nullable=False),
        sa.Column("billing_type", sa.String(length=30), nullable=False),
        sa.Column(
            "monthly_price", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "yearly_price", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "per_bill_price", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("trial_days", sa.Integer(), nullable=False),
        sa.Column("features", sa.Text(), nullable=True),
        sa.Column("limits", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_plans_plan_id"),
        "subscription_plans",
        ["plan_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscription_plans_plan_id"), table_name="subscription_plans"
    )
    op.drop_table("subscription_plans")
    # ### end Alembic commands ###
