"""add customer uploaded bills

Revision ID: 2a52943bbabe
Revises: 2e73ec51031a
Create Date: 2026-09-19 15:58:27.771835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a52943bbabe"
down_revision: Union[str, Sequence[str], None] = "2e73ec51031a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_uploaded_bills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bill_id", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("razorpay_order_id", sa.String(length=100), nullable=True),
        sa.Column("razorpay_payment_id", sa.String(length=100), nullable=True),
        sa.Column(
            "transaction_reference", sa.String(length=255), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_uploaded_bills_bill_id"),
        "customer_uploaded_bills",
        ["bill_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_customer_uploaded_bills_customer_id"),
        "customer_uploaded_bills",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_uploaded_bills_razorpay_order_id"),
        "customer_uploaded_bills",
        ["razorpay_order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_customer_uploaded_bills_razorpay_payment_id"),
        "customer_uploaded_bills",
        ["razorpay_payment_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_uploaded_bills_razorpay_payment_id"),
        table_name="customer_uploaded_bills",
    )
    op.drop_index(
        op.f("ix_customer_uploaded_bills_razorpay_order_id"),
        table_name="customer_uploaded_bills",
    )
    op.drop_index(
        op.f("ix_customer_uploaded_bills_customer_id"),
        table_name="customer_uploaded_bills",
    )
    op.drop_index(
        op.f("ix_customer_uploaded_bills_bill_id"),
        table_name="customer_uploaded_bills",
    )
    op.drop_table("customer_uploaded_bills")
    # ### end Alembic commands ###
