"""link transfers and ownership history to product units

Revision ID: 3109c0e7d397
Revises: df95ce98256e
Create Date: 2026-08-13 12:12:38.147254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3109c0e7d397"
down_revision: Union[str, Sequence[str], None] = "df95ce98256e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ownership_history",
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
    )
    op.drop_constraint(
        op.f("ownership_history_product_variant_id_fkey"),
        "ownership_history",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "ownership_history",
        "product_units",
        ["product_unit_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("ownership_history", "product_variant_id")
    op.add_column(
        "product_transfers",
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
    )
    op.drop_constraint(
        op.f("product_transfers_product_variant_id_fkey"),
        "product_transfers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "product_transfers",
        "product_units",
        ["product_unit_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("product_transfers", "product_variant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_transfers",
        sa.Column(
            "product_variant_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "product_transfers", type_="foreignkey")
    op.create_foreign_key(
        op.f("product_transfers_product_variant_id_fkey"),
        "product_transfers",
        "product_variants",
        ["product_variant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("product_transfers", "product_unit_id")
    op.add_column(
        "ownership_history",
        sa.Column(
            "product_variant_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "ownership_history", type_="foreignkey")
    op.create_foreign_key(
        op.f("ownership_history_product_variant_id_fkey"),
        "ownership_history",
        "product_variants",
        ["product_variant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("ownership_history", "product_unit_id")
    # ### end Alembic commands ###
