"""add purchase returns

Revision ID: 514754f68c54
Revises: 72a5fa64b159
Create Date: 2026-08-12 18:45:46.922067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "514754f68c54"
down_revision: Union[str, Sequence[str], None] = "72a5fa64b159"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_returns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("return_id", sa.String(length=30), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("retailer_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("processed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "return_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"], ["inventory_locations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"], ["purchase_orders.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"], ["retailers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_returns_return_id"),
        "purchase_returns",
        ["return_id"],
        unique=True,
    )
    op.create_table(
        "purchase_return_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_return_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_item_id", sa.Uuid(), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "unit_cost", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "return_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("condition", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_item_id"],
            ["purchase_order_items.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_return_id"], ["purchase_returns.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchase_return_items")
    op.drop_index(
        op.f("ix_purchase_returns_return_id"), table_name="purchase_returns"
    )
    op.drop_table("purchase_returns")
    # ### end Alembic commands ###
