"""add salesman commission tracking

Revision ID: 95c5fcab5f63
Revises: allow_phone_account_types
Create Date: 2026-09-06 23:30:17.525921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95c5fcab5f63"
down_revision: Union[str, Sequence[str], None] = "allow_phone_account_types"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salesman_commissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("salesman_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column(
            "sale_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "commission_rate", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "commission_amount",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "paid_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "pending_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["salesman_id"], ["employees.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_salesman_commissions_salesman_id"),
        "salesman_commissions",
        ["salesman_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_salesman_commissions_subscription_id"),
        "salesman_commissions",
        ["subscription_id"],
        unique=True,
    )
    op.add_column(
        "subscriptions", sa.Column("salesman_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_subscriptions_salesman_id"),
        "subscriptions",
        ["salesman_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "subscriptions",
        "employees",
        ["salesman_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    op.drop_index(
        op.f("ix_subscriptions_salesman_id"), table_name="subscriptions"
    )
    op.drop_column("subscriptions", "salesman_id")
    op.drop_index(
        op.f("ix_salesman_commissions_subscription_id"),
        table_name="salesman_commissions",
    )
    op.drop_index(
        op.f("ix_salesman_commissions_salesman_id"),
        table_name="salesman_commissions",
    )
    op.drop_table("salesman_commissions")
    # ### end Alembic commands ###
