"""add password reset tokens

Revision ID: bbe3b903d94c
Revises: 4f3578f2baec
Create Date: 2026-09-09 20:01:09.885722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbe3b903d94c"
down_revision: Union[str, Sequence[str], None] = "4f3578f2baec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.alter_column(
        "invoices",
        "customer_bill_charge",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "payment_configurations",
        "customer_bill_charge",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "payment_configurations",
        "customer_transfer_fee",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=False
    )
    op.alter_column(
        "payment_configurations",
        "customer_transfer_fee",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        server_default=sa.text("9.00"),
        existing_nullable=False,
    )
    op.alter_column(
        "payment_configurations",
        "customer_bill_charge",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        server_default=sa.text("5.00"),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "customer_bill_charge",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        server_default=sa.text("0.00"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
