"""add payment configuration

Revision ID: f08eaa40c0d6
Revises: be95915668ec
Create Date: 2026-08-17 16:09:22.161490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f08eaa40c0d6"
down_revision: Union[str, Sequence[str], None] = "be95915668ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_configurations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "per_bill_charge",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column("max_cash_due_invoices", sa.Integer(), nullable=False),
        sa.Column(
            "annual_subscription_price",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "salesman_commission_percent",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_configurations")
    # ### end Alembic commands ###
