"""add billing usage

Revision ID: 3ba4d40c4d17
Revises: 3243862cd8f7
Create Date: 2026-08-15 22:03:31.610876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ba4d40c4d17"
down_revision: Union[str, Sequence[str], None] = "3243862cd8f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("usage_id", sa.String(length=30), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column(
            "billing_period_start", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "billing_period_end", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "unit_price", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_usage_usage_id"),
        "billing_usage",
        ["usage_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_billing_usage_usage_id"), table_name="billing_usage"
    )
    op.drop_table("billing_usage")
    # ### end Alembic commands ###
