"""Add invoice item unit mapping

Revision ID: 6967f8972607
Revises: 3109c0e7d397
Create Date: 2026-08-13 18:14:39.728271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6967f8972607"
down_revision: Union[str, Sequence[str], None] = "3109c0e7d397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_item_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_item_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_item_id"], ["invoice_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"], ["product_units.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invoice_item_units")
    # ### end Alembic commands ###
