"""Add sales return item unit mapping

Revision ID: 973b68b6ecc3
Revises: 6967f8972607
Create Date: 2026-08-13 19:11:44.865636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "973b68b6ecc3"
down_revision: Union[str, Sequence[str], None] = "6967f8972607"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_return_item_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sales_return_item_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_unit_id"], ["product_units.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["sales_return_item_id"],
            ["sales_return_items.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sales_return_item_units")
    # ### end Alembic commands ###
