"""add invoice billing periods

Revision ID: be95915668ec
Revises: a1b2c3d4e5f6
Create Date: 2026-08-16 10:43:59.180396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be95915668ec"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column(
            "billing_period_start", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "billing_period_end", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "billing_period_end")
    op.drop_column("invoices", "billing_period_start")
    # ### end Alembic commands ###
